### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by swandog30** [christiandaley/Spartan#1]
I was able to build this with TDM-GCC-32 4.9 after resolving these two issues:
1. Included stdint.h for the uint64_t type
2. Added the -std=c99 compiler flag to allow for the for loop initial declarations.

**Comment by christiandaley** [comment]
Hi, thanks for the feedback.

I included stdint.h in all the files that use the uint64_t type. Also, the makefile already had -std=c99 in the compile flags. Anyways, I removed all variable declarations in for loops so it shouldn't be a problem now.
